name: start worker2
#on: 
#  push:
#    branches:
#      - main
on:
  schedule:
    - cron:  '5 22 * * *'   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main
    - name: install depends
      run: |
          sudo apt-get update
          sudo apt-get install -y git python3 sudo python3-pip
          sudo pip3 install requests          
    - name: runs
      env:
        COMMIT_MSG: |
          addcommit
          skip-checks: true
      run: |
          sudo python3 worker2.py ${{ secrets.ACCESS_TOKEN }}
